# Generated by Django 2.0.1 on 2018-01-04 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ori', models.TextField(choices=[('FAKE ORI', 'FAKE ORI')], unique=True, verbose_name='ORI')),
                ('name', models.TextField(verbose_name='Agency name')),
                ('agency_type', models.TextField(choices=[('city', 'city'), ('county', 'county')], verbose_name='Agency type')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.TextField(choices=[('all', 'all'), ('estimated', 'estimated'), ('raw', 'raw')])),
                ('annontation_type', models.TextField(choices=[('caveat', 'Caveat'), ('footnote', 'Footnote')])),
                ('annotation_text', models.TextField(blank=True, null=True)),
                ('agency_ori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='footnotes.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='USState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('AK', 'Alaska'), ('CA', 'California'), ('ID', 'Idaho'), ('NY', 'New York'), ('WV', 'West Virginia')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017')], unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='offense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='footnotes.Offense'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='us_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='footnotes.USState'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='years',
            field=models.ManyToManyField(blank=True, to='footnotes.Year'),
        ),
        migrations.AddField(
            model_name='agency',
            name='us_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footnotes.USState'),
        ),
    ]
